create extension if not exists pgcrypto;

create table if not exists public.firms (
    id bigint generated by default as identity primary key,
    name text not null,
    website_url text,
    hq_city text,
    hq_state text,
    market text,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint firms_name_website_unique unique (name, website_url)
);

create table if not exists public.firm_sources (
    id bigint generated by default as identity primary key,
    firm_id bigint not null references public.firms(id) on delete cascade,
    source_type text not null,
    url text not null,
    title text,
    snippet text,
    raw_text text,
    fetched_at timestamptz not null default now(),
    constraint firm_sources_firm_url_unique unique (firm_id, url)
);

create table if not exists public.firm_scores (
    id bigint generated by default as identity primary key,
    firm_id bigint not null references public.firms(id) on delete cascade,
    land_development_focus integer not null,
    civil_3d_likelihood integer not null,
    drafting_intensity integer not null,
    ai_fit integer not null,
    firm_size integer not null,
    total_score integer not null,
    decision text not null,
    reasoning text not null,
    scored_at timestamptz not null default now()
);

create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    firm_id bigint not null references public.firms(id) on delete cascade,
    full_name text,
    title text,
    email text,
    phone text,
    profile_url text,
    source_url text,
    confidence integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.research_runs (
    id bigint generated by default as identity primary key,
    geo text not null,
    status text not null,
    requested_limit integer not null,
    notes text,
    started_at timestamptz not null default now(),
    completed_at timestamptz
);

create table if not exists public.research_run_firms (
    research_run_id bigint not null references public.research_runs(id) on delete cascade,
    firm_id bigint not null references public.firms(id) on delete cascade,
    rank integer,
    primary key (research_run_id, firm_id)
);

create index if not exists idx_firm_scores_total on public.firm_scores(total_score desc);
create index if not exists idx_firm_scores_firm_id on public.firm_scores(firm_id);
create index if not exists idx_firms_market on public.firms(market);
create index if not exists idx_contacts_firm on public.contacts(firm_id);
create index if not exists idx_research_run_firms_firm_id on public.research_run_firms(firm_id);

alter table public.firms enable row level security;
alter table public.firm_sources enable row level security;
alter table public.firm_scores enable row level security;
alter table public.contacts enable row level security;
alter table public.research_runs enable row level security;
alter table public.research_run_firms enable row level security;

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

revoke all on public.firms from anon, authenticated;
revoke all on public.firm_sources from anon, authenticated;
revoke all on public.firm_scores from anon, authenticated;
revoke all on public.contacts from anon, authenticated;
revoke all on public.research_runs from anon, authenticated;
revoke all on public.research_run_firms from anon, authenticated;
